name: Flutter

on:
  push:
    branches: [ "main" ]
    paths:
      - "flutter_frontend/**"

jobs:
  flutter_test:
    name: Flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up flutter actions
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install flutter packages
        run: flutter pub get
        working-directory: ./flutter_frontend
      - name: Analyze flutter code
        run: flutter analyze
        working-directory: ./flutter_frontend
      - name: Run flutter test
        run: flutter test
        working-directory: ./flutter_frontend


  build_ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [ flutter_test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up flutter actions
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install flutter packages
        run: flutter pub get
        working-directory: ./flutter_frontend
      - name: Clean flutter project
        run: flutter clean
        working-directory: ./flutter_frontend
      - name: Build iOS
        run: flutter build ios --no-codesign
        working-directory: ./flutter_frontend

  build_android:
    name: Build android
    runs-on: ubuntu-latest
    needs: [ flutter_test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up flutter actions
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install flutter packages
        run: flutter pub get
        working-directory: ./flutter_frontend
      - name: Clean flutter project
        run: flutter clean
        working-directory: ./flutter_frontend
      - name: Build android
        run: flutter build appbundle
        working-directory: ./flutter_frontend